"""baseline schema (pre-ops-substrate)

Captures the schema as created by ``Base.metadata.create_all()`` from
backend/db/models.py prior to the Task 2 schema fixes (revision 0002):
``courses.created_at``/``updated_at`` are plain strings and
``chapters.assets`` still exists. Hand-written (not autogenerated) so it can
be used to ``alembic stamp`` pre-existing databases that were created via
``create_all`` before Alembic was introduced.

Revision ID: 0001
Revises:
Create Date: 2026-07-04
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "courses",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("generation_status", sa.String(), nullable=True),
        sa.Column("generation_progress", sa.JSON(), nullable=True),
        sa.Column("generation_last_error", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=True),
    )
    op.create_table(
        "plan_items",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("course_id", sa.String(), sa.ForeignKey("courses.id"), nullable=False),
        sa.Column("section_id", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("objectives", sa.JSON(), nullable=True),
        sa.Column("importance", sa.String(), nullable=True),
        sa.Column("prerequisites", sa.JSON(), nullable=True),
        sa.Column("target_words", sa.Integer(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
    )
    op.create_table(
        "chapters",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("course_id", sa.String(), sa.ForeignKey("courses.id"), nullable=False),
        sa.Column("section_id", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("objectives", sa.JSON(), nullable=True),
        sa.Column("importance", sa.String(), nullable=True),
        sa.Column("source_pages", sa.JSON(), nullable=True),
        sa.Column("assets", sa.JSON(), nullable=True),
        sa.Column("body_md", sa.TEXT(), nullable=True),
        sa.Column("quiz", sa.JSON(), nullable=True),
        sa.Column("cards", sa.JSON(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("lesson_md", sa.TEXT(), nullable=True),
        sa.Column("lesson_status", sa.String(), nullable=True),
    )
    op.create_table(
        "assets",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("course_id", sa.String(), sa.ForeignKey("courses.id"), nullable=False),
        sa.Column("path", sa.String(), nullable=True),
        sa.Column("source_page", sa.Integer(), nullable=True),
        sa.Column("caption", sa.String(), nullable=True),
    )
    op.create_table(
        "progress_states",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("course_id", sa.String(), sa.ForeignKey("courses.id"), nullable=False),
        sa.Column("section_id", sa.String(), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=True),
        sa.Column("last_viewed_at", sa.String(), nullable=True),
    )
    op.create_table(
        "review_states",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("course_id", sa.String(), sa.ForeignKey("courses.id"), nullable=False),
        sa.Column("section_id", sa.String(), nullable=True),
        sa.Column("card_index", sa.Integer(), nullable=True),
        sa.Column("ease", sa.Float(), nullable=True),
        sa.Column("interval", sa.Integer(), nullable=True),
        sa.Column("due_at", sa.String(), nullable=True),
        sa.Column("reps", sa.Integer(), nullable=True),
    )
    op.create_table(
        "review_logs",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("course_id", sa.String(), sa.ForeignKey("courses.id"), nullable=False),
        sa.Column("section_id", sa.String(), nullable=True),
        sa.Column("card_index", sa.Integer(), nullable=True),
        sa.Column("quality", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
    )
    op.create_table(
        "chat_turns",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("course_id", sa.String(), sa.ForeignKey("courses.id"), nullable=False),
        sa.Column("section_id", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("content", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("citations", sa.JSON(), nullable=True),
    )
    op.create_table(
        "chunks",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("course_id", sa.String(), sa.ForeignKey("courses.id"), nullable=False),
        sa.Column("source_ref", sa.String(), nullable=False),
        sa.Column("content", sa.TEXT(), nullable=False),
        sa.Column("embedding", sa.JSON(), nullable=True),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
    )
    op.create_table(
        "test_attempts",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("course_id", sa.String(), sa.ForeignKey("courses.id"), nullable=False),
        sa.Column("section_id", sa.String(), nullable=True),
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("answers", sa.JSON(), nullable=True),
        sa.Column("correct", sa.Integer(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=True),
    )


def downgrade() -> None:
    op.drop_table("test_attempts")
    op.drop_table("chunks")
    op.drop_table("chat_turns")
    op.drop_table("review_logs")
    op.drop_table("review_states")
    op.drop_table("progress_states")
    op.drop_table("assets")
    op.drop_table("chapters")
    op.drop_table("plan_items")
    op.drop_table("courses")
